spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true # ??? ???? ???? ????? ??? ??
        default_batch_fetch_size: 100 # N+1 ???? ???? ?? ??? ???. ??? 100?? ??? ??(?)
    hibernate:
      ddl-auto: create