### 계정 생성
POST http://localhost:8080/user/add
Content-Type: application/json

{
  "username" : "kurt",
  "password" : 12345
}

### OTP 생성
POST http://localhost:8080/user/auth
Content-Type: application/json

{
  "username" : "kurt",
  "password" : 12345
}

### OTP 검사
POST http://localhost:8080/otp/check
Content-Type: application/json

{
  "username": "kurt",
  "code": 6538
}